# Generated by Django 4.0.3 on 2022-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointmentModel',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Enter Your Name')),
                ('gmail', models.EmailField(help_text='Enter Gmail', max_length=254)),
                ('password', models.CharField(help_text='Enter Password', max_length=200)),
            ],
        ),
    ]
