# Generated by Django 4.0.3 on 2022-03-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorappointmentmodel',
            table='Appointment Details',
        ),
    ]
