# Generated by Django 4.0.3 on 2022-03-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_doctorappointmentmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorappointmentmodel',
            table='Appointment_Details',
        ),
    ]
