# Generated by Django 4.0.3 on 2022-03-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_doctorappointmentmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointmentmodel',
            name='gmail',
            field=models.EmailField(help_text='Enter Gmail', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorappointmentmodel',
            name='name',
            field=models.TextField(help_text='Enter Your Name', max_length=200),
        ),
    ]
